import BeefEmpanadas from "../assets/beefempanada.jpg";
import BeefEmpanadasSmall from "../assets/beefempanada(1).jpg";
import HomemadeSalsa from "../assets/salsa.jpg";
import HomemadeQueso from "../assets/queso.jpg";
import SalsaVerde from "../assets/salsaverde.jpg";
import RefriendBeanDip from "../assets/beandip.jpg";
import StreetTaco from "../assets/streettaco.jpg";
import Tamales from "../assets/tamales.jpg";
import Birria from "../assets/birria.jpg";
import Gorditas from "../assets/gorditas.jpg";
import GorditasSmall from "../assets/gorditas(1).jpg";
import QuesoFundido from "../assets/quesofundido.jpg";
import ConchaBread from "../assets/conchabread.jpg";
import Churros from "../assets/churros.jpg";
import MargaritaTart from "../assets/margaritatart.jpg";
import Chocoflan from "../assets/chocoflan.jpg";
import ChocoflanSmall from "../assets/chocoflan(1).jpg";
import TresLeches from "../assets/tresleches.jpg";
import Champurrado from "../assets/champurrado.jpg";
import Margarita from "../assets/margarita.jpg";
import Horchata from "../assets/horchata.jpg";
import AquaDeJamaica from "../assets/aguadejamaica.jpg";
import AquasFrescas from "../assets/aguafresca.jpg";
import AquasFrescasSmall from "../assets/aguafresca(1).jpg";
import Nachos from "../assets/nachos.jpg";
import Taquitos from "../assets/taquitos.jpg";
import FritoPie from "../assets/fritopie.jpg";
import FritoPieSmall from "../assets/fritopie(1).jpg";
import Enchiladas from "../assets/enchiladas.jpg";
import Tacos from "../assets/tacos.jpg";

export const recipes = [
  {
    id: 1,
    img: BeefEmpanadas,
    imgSmall: BeefEmpanadasSmall,
    title: "Beef Empanadas",
    description:
      "A delicious Latin American pastry filled with seasoned ground beef, olives, and raisins.",
    ingredients: [
      "2 1/2 cups all-purpose flour",
      "1/2 teaspoon salt",
      "1/2 cup unsalted butter (cold and cut into small cubes)",
      "1/2 cup cold water",
      "1 lb ground beef",
      "1 medium onion, finely chopped",
      "2 garlic cloves, minced",
      "1/2 cup green olives, pitted and chopped",
      "1/4 cup raisins",
      "1 tablespoon ground cumin",
      "1 teaspoon paprika",
      "1/2 teaspoon chili powder (optional, for added spice)",
      "Salt and pepper to taste",
      "2 tablespoons olive oil (for cooking)",
      "1 egg (optional, for egg wash)",
      "1 tablespoon water (optional, for egg wash)",
    ],
    instructions: [
      "Prepare the dough:",
      "In a large mixing bowl, combine the flour and salt.",
      "Add the cold cubed butter and work it into the flour using your hands or a pastry cutter until the mixture resembles coarse crumbs.",
      "Slowly add cold water and knead until the dough comes together and is smooth.",
      "Form the dough into a ball, cover it with plastic wrap, and refrigerate for at least 30 minutes.",
      "Prepare the beef filling:",
      "In a large skillet or frying pan, heat the olive oil over medium heat.",
      "Add the chopped onions and cook until they become translucent.",
      "Add the minced garlic and ground beef to the pan. Cook until the beef is browned and cooked through.",
      "Stir in the chopped olives, raisins, cumin, paprika, chili powder (if using), salt, and pepper. Mix well to combine all the ingredients.",
      "Let the filling cool down to room temperature.",
      "Assemble the empanadas:",
      "Take the chilled dough out of the refrigerator and roll it out on a floured surface until it's about 1/8 inch thick.",
      "Use a round cutter or a small plate to cut circles from the dough (around 5 to 6 inches in diameter).",
      "Place a spoonful of the beef filling in the center of each dough circle.",
      "Fold the dough over the filling to create a half-moon shape. Press the edges together firmly to seal the empanada. You can use the tines of a fork to crimp the edges for a decorative touch.",
      "If using an egg wash, whisk together the egg and water in a small bowl. Brush the top of each empanada with the egg wash. This will give them a shiny and golden appearance when baked.",
      "Bake the empanadas:",
      "Arrange the assembled empanadas on a baking sheet lined with parchment paper.",
      "Preheat your oven to 375°F (190°C) while you assemble the empanadas.",
      "Bake in the preheated oven for about 20-25 minutes or until the empanadas are golden brown and crispy.",
      "Serve:",
      "Let the empanadas cool slightly before serving, as the filling will be hot.",
      "Enjoy your authentic beef empanadas as a delicious appetizer, snack, or part of a meal.",
    ],
    recipeType: "appetizer",
    isFavorite: false,
    isWeekly: true,
    time: "90 min",
  },
  {
    id: 2,
    img: HomemadeSalsa,
    title: "Homemade Salsa",
    description:
      "A classic and flavorful tomato-based salsa made with fresh ingredients.",
    ingredients: [
      "5 ripe tomatoes, diced",
      "1/2 red onion, finely chopped",
      "1 jalapeño or serrano chili, seeded and finely chopped",
      "1/4 cup fresh cilantro, chopped",
      "2 cloves garlic, minced",
      "Juice of 1 lime",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a medium bowl, combine the diced tomatoes, chopped red onion, chopped chili, cilantro, and minced garlic.",
      "Squeeze the lime juice over the mixture and season with salt and pepper to taste.",
      "Stir everything together until well combined.",
      "Cover the bowl and refrigerate for at least 30 minutes to allow the flavors to meld.",
      "Serve the homemade salsa with tortilla chips or as a topping for tacos, burritos, and other Mexican dishes.",
      "Enjoy your fresh and delicious homemade salsa!",
    ],
    recipeType: "appetizer",
    isFavorite: false,
    isWeekly: false,
    time: "30 min",
  },
  {
    id: 3,
    img: HomemadeQueso,
    title: "Queso Dip",
    description:
      "Creamy and cheesy queso dip perfect for dipping tortilla chips or topping nachos.",
    ingredients: [
      "1 lb (16 oz) white American cheese, shredded or diced",
      "1 cup whole milk or half-and-half",
      "1 can (10 oz) diced tomatoes with green chilies, drained",
      "1 teaspoon ground cumin",
      "1/2 teaspoon chili powder",
      "1/4 teaspoon garlic powder",
      "1/4 teaspoon onion powder",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a medium saucepan, heat the milk or half-and-half over medium heat until hot but not boiling.",
      "Add the shredded or diced white American cheese to the saucepan and stir continuously until the cheese is melted and smooth.",
      "Stir in the diced tomatoes with green chilies, ground cumin, chili powder, garlic powder, onion powder, salt, and pepper.",
      "Continue to cook and stir until the queso dip is heated through and well combined.",
      "Adjust seasoning with more salt and pepper if needed.",
      "Transfer the queso dip to a serving bowl and garnish with chopped cilantro or additional diced tomatoes if desired.",
      "Serve the queso dip warm with tortilla chips or as a topping for nachos.",
      "Enjoy your creamy and flavorful queso dip!",
    ],
    recipeType: "appetizer",
    isFavorite: false,
    isWeekly: false,
    time: "45 min",
  },
  {
    id: 4,
    img: SalsaVerde,
    title: "Salsa Verde",
    description:
      "A tangy and vibrant green salsa made with tomatillos and fresh cilantro.",
    ingredients: [
      "1 lb tomatillos, husked and rinsed",
      "1/2 white onion, chopped",
      "2 cloves garlic",
      "1 jalapeño or serrano chili, chopped (seeds removed for less heat)",
      "1/4 cup fresh cilantro, chopped",
      "Juice of 1 lime",
      "Salt to taste",
    ],
    instructions: [
      "Preheat the broiler in your oven.",
      "Place the husked and rinsed tomatillos on a baking sheet, along with the chopped white onion and garlic cloves.",
      "Broil the vegetables for about 5 minutes or until they are slightly charred and softened.",
      "Remove the baking sheet from the oven and let the ingredients cool for a few minutes.",
      "In a blender or food processor, combine the broiled tomatillos, onion, garlic, chopped chili, cilantro, and lime juice.",
      "Blend until you achieve the desired consistency.",
      "Season the salsa verde with salt to taste.",
      "Transfer the salsa verde to a serving bowl.",
      "Refrigerate the salsa verde for at least 30 minutes before serving to allow the flavors to develop.",
      "Serve the tangy and vibrant salsa verde with tortilla chips or as a condiment for tacos, enchiladas, and other dishes.",
      "Enjoy your homemade salsa verde!",
    ],
    recipeType: "appetizer",
    isFavorite: false,
    isWeekly: false,
    time: "20 min",
  },
  {
    id: 5,
    img: RefriendBeanDip,
    title: "Refried Beans",
    description:
      "Creamy and flavorful refried beans, a perfect side dish for many Mexican meals.",
    ingredients: [
      "2 cups cooked pinto beans (or 1 can of pinto beans, drained and rinsed)",
      "2 tablespoons vegetable oil or lard",
      "1/2 onion, finely chopped",
      "2 cloves garlic, minced",
      "1 teaspoon ground cumin",
      "1/2 teaspoon chili powder",
      "Salt and pepper to taste",
      "1/4 cup water (or bean cooking liquid)",
    ],
    instructions: [
      "In a large skillet, heat the vegetable oil or lard over medium heat.",
      "Add the finely chopped onion and cook until it becomes translucent.",
      "Add the minced garlic to the skillet and cook for another minute until fragrant.",
      "Stir in the cooked pinto beans and mash them with a potato masher or the back of a spoon.",
      "Season the beans with ground cumin, chili powder, salt, and pepper. Mix well to incorporate the seasonings.",
      "Add the water or bean cooking liquid to the skillet to achieve your desired consistency. Cook for a few minutes until the beans are heated through and creamy.",
      "Adjust seasoning with more salt and pepper if needed.",
      "Transfer the refried beans to a serving bowl.",
      "Serve the creamy and flavorful refried beans as a delicious side dish for tacos, burritos, enchiladas, and more.",
      "Enjoy your homemade refried beans!",
    ],
    recipeType: "appetizer",
    isFavorite: false,
    isWeekly: false,
    time: "60 min",
  },
  {
    id: 6,
    img: StreetTaco,
    title: "Carne Asada Street Tacos",
    description:
      "Delicious and tender grilled beef served in warm corn tortillas with fresh toppings.",
    ingredients: [
      "1 lb flank steak or skirt steak",
      "1/4 cup orange juice",
      "1/4 cup lime juice",
      "3 cloves garlic, minced",
      "1/4 cup fresh cilantro, chopped",
      "1 teaspoon ground cumin",
      "1 teaspoon chili powder",
      "Salt and pepper to taste",
      "Corn tortillas",
      "Chopped onion, fresh cilantro, diced tomatoes, and lime wedges for serving",
    ],
    instructions: [
      "In a bowl, mix the orange juice, lime juice, minced garlic, chopped cilantro, ground cumin, chili powder, salt, and pepper to create the marinade.",
      "Place the flank steak or skirt steak in a resealable plastic bag or a shallow dish and pour the marinade over the meat.",
      "Close the bag or cover the dish and marinate the steak in the refrigerator for at least 2 hours or overnight for maximum flavor.",
      "Preheat the grill or a skillet over high heat.",
      "Remove the steak from the marinade and grill or cook in the skillet for about 4-6 minutes per side or until it reaches your desired level of doneness.",
      "Let the meat rest for a few minutes before slicing it thinly against the grain.",
      "Warm the corn tortillas on the grill or in a skillet for a minute on each side.",
      "Assemble the carne asada street tacos by placing some sliced grilled meat on each tortilla.",
      "Top with chopped onion, fresh cilantro, diced tomatoes, and a squeeze of lime juice.",
      "Serve the delicious carne asada street tacos with your favorite salsa or hot sauce.",
      "Enjoy the authentic flavors of Mexican street food!",
    ],
    recipeType: "dishes",
    isFavorite: false,
    isWeekly: false,
    time: "45 min",
  },
  {
    id: 7,
    img: Tamales,
    title: "Pork Tamales",
    description:
      "Traditional tamales filled with seasoned pork and wrapped in corn husks.",
    ingredients: [
      "1 package dried corn husks",
      "2 cups masa harina",
      "2 cups pork broth or chicken broth",
      "1 cup lard or vegetable shortening",
      "1 teaspoon baking powder",
      "1/2 teaspoon salt",
      "2 cups shredded cooked pork (seasoned with chili powder, cumin, and garlic)",
      "Your favorite salsa or hot sauce for serving",
    ],
    instructions: [
      "Place the dried corn husks in a large bowl and cover them with warm water. Let them soak for at least 30 minutes until they become pliable.",
      "In a large mixing bowl, beat the lard or vegetable shortening with a mixer until fluffy.",
      "In a separate bowl, combine the masa harina, baking powder, and salt.",
      "Gradually add the masa mixture to the beaten lard, alternating with the pork broth, until you achieve a smooth dough.",
      "Drain the corn husks and pat them dry.",
      "Spread a thin layer of masa dough on each corn husk, leaving space at the edges.",
      "Place a spoonful of shredded seasoned pork in the center of the masa on each husk.",
      "Fold the sides of the corn husk inward to cover the filling and fold the bottom of the husk up.",
      "Place the tamales in a steamer basket with the open end facing up.",
      "Steam the tamales over medium-high heat for about 1 to 1.5 hours or until the masa is firm and cooked through.",
      "Let the tamales rest for a few minutes before unwrapping and serving.",
      "Serve the delicious pork tamales with your favorite salsa or hot sauce.",
      "Enjoy the traditional and flavorful taste of Mexican tamales!",
    ],
    recipeType: "dishes",
    isFavorite: false,
    isWeekly: false,
    time: "4 hrs",
  },
  {
    id: 8,
    img: Birria,
    title: "Birria",
    description:
      "A flavorful Mexican stew made with tender meat and spices, often served in tacos.",
    ingredients: [
      "3 lbs beef chuck roast or goat meat, cut into chunks",
      "1/2 onion, chopped",
      "4 cloves garlic, minced",
      "2 bay leaves",
      "1 cinnamon stick",
      "1 tablespoon ground cumin",
      "1 tablespoon dried oregano",
      "2 teaspoons smoked paprika",
      "2 teaspoons chili powder",
      "Salt and pepper to taste",
      "4 cups beef broth or water",
      "Dried chilies (guajillo, ancho, or a combination) soaked in hot water",
      "Corn tortillas, chopped onions, fresh cilantro, and lime wedges for serving",
    ],
    instructions: [
      "In a large pot or Dutch oven, heat some oil over medium-high heat.",
      "Add the chopped onion and minced garlic. Sauté until the onion becomes translucent.",
      "Add the beef or goat meat chunks and brown them on all sides.",
      "Stir in the bay leaves, cinnamon stick, ground cumin, dried oregano, smoked paprika, chili powder, salt, and pepper.",
      "Pour in the beef broth or water, and bring the mixture to a boil.",
      "Reduce the heat to low, cover the pot, and simmer for about 2 to 3 hours or until the meat is tender and falls apart easily.",
      "While the meat cooks, make the birria sauce by blending the soaked dried chilies with a bit of the soaking liquid until you get a smooth sauce.",
      "Once the meat is tender, remove the cinnamon stick and bay leaves.",
      "Stir in the birria sauce and let the stew simmer for an additional 20-30 minutes to meld the flavors.",
      "Serve the birria in tacos with chopped onions, fresh cilantro, and a squeeze of lime juice.",
      "Enjoy the rich and flavorful birria stew in the form of delicious tacos!",
    ],
    recipeType: "dishes",
    isFavorite: true,
    isWeekly: false,
    time: "4 hrs",
  },
  {
    id: 9,
    img: Gorditas,
    imgSmall: GorditasSmall,
    title: "Gorditas",
    description:
      "Thick and soft corn cakes stuffed with savory fillings, a popular Mexican street food.",
    ingredients: [
      "2 cups masa harina",
      "1 1/4 cups warm water",
      "1/2 teaspoon salt",
      "1 cup refried beans",
      "1 cup cooked and shredded chicken or beef",
      "Chopped lettuce, diced tomatoes, crumbled queso fresco, and your favorite salsa for serving",
    ],
    instructions: [
      "In a large mixing bowl, combine the masa harina, warm water, and salt to create the dough.",
      "Knead the dough until it becomes smooth and pliable. If needed, add more water or masa harina to adjust the consistency.",
      "Divide the dough into small balls, about the size of a golf ball.",
      "Flatten each ball into a thick disk using your hands or a tortilla press.",
      "Heat a griddle or a skillet over medium-high heat.",
      "Cook the gorditas on the hot griddle for about 2-3 minutes on each side or until they are lightly browned and cooked through.",
      "Remove the gorditas from the griddle and let them cool slightly.",
      "Carefully slice each gordita in half, creating a pocket for the filling.",
      "Fill the gorditas with a spoonful of refried beans and some cooked and shredded chicken or beef.",
      "Top the gorditas with chopped lettuce, diced tomatoes, crumbled queso fresco, and your favorite salsa.",
      "Serve the delicious gorditas as a flavorful and satisfying Mexican street food.",
      "Enjoy the tasty and hearty gorditas with your choice of fillings!",
    ],
    recipeType: "dishes",
    isFavorite: false,
    isWeekly: true,
    time: "60 min",
  },
  {
    id: 10,
    img: QuesoFundido,
    title: "Queso Fundido",
    description:
      "A gooey and indulgent melted cheese dish, often flavored with chorizo or mushrooms.",
    ingredients: [
      "2 cups shredded Oaxaca cheese or Monterey Jack cheese",
      "1/2 cup crumbled queso fresco",
      "1/4 cup chopped onion",
      "1/4 cup chopped fresh cilantro",
      "1/4 cup chopped pickled jalapeños (optional, for extra spice)",
      "Cooked chorizo or sautéed mushrooms (optional, for additional flavor)",
      "Tortilla chips or warm tortillas for serving",
    ],
    instructions: [
      "Preheat your oven to 375°F (190°C).",
      "In a small cast-iron skillet or a baking dish, layer half of the shredded cheese.",
      "Add a layer of chopped onions, chopped cilantro, and pickled jalapeños (if using).",
      "Add a layer of cooked chorizo or sautéed mushrooms (if using).",
      "Top with the remaining shredded cheese and the crumbled queso fresco.",
      "Bake in the preheated oven for about 15 minutes or until the cheese is completely melted and bubbly.",
      "Remove the queso fundido from the oven and let it cool slightly.",
      "Serve the queso fundido hot with tortilla chips or warm tortillas for dipping.",
      "Enjoy the gooey and flavorful queso fundido as a delicious and indulgent appetizer.",
    ],
    recipeType: "dishes",
    isFavorite: false,
    isWeekly: false,
    time: "30 min",
  },
  {
    id: 11,
    img: ConchaBread,
    title: "Concha Bread",
    description:
      "A sweet and iconic Mexican pastry with a sugary topping shaped like a seashell.",
    ingredients: [
      "4 cups all-purpose flour",
      "1/2 cup granulated sugar",
      "1/2 teaspoon salt",
      "2 1/4 teaspoons active dry yeast",
      "1/2 cup warm milk",
      "1/4 cup warm water",
      "1/3 cup unsalted butter, softened",
      "1 teaspoon vanilla extract",
      "3 large eggs",
      "For the topping:",
      "1/2 cup unsalted butter, softened",
      "1/2 cup granulated sugar",
      "3/4 cup all-purpose flour",
      "1 teaspoon vanilla extract",
      "Food coloring (optional)",
    ],
    instructions: [
      "In a large mixing bowl, combine the all-purpose flour, granulated sugar, and salt.",
      "In a separate small bowl, dissolve the active dry yeast in warm milk and warm water. Let it sit for a few minutes until it becomes frothy.",
      "Add the yeast mixture, softened unsalted butter, vanilla extract, and eggs to the dry ingredients.",
      "Mix everything together until you have a smooth and elastic dough.",
      "Cover the bowl with plastic wrap and let the dough rise in a warm place for about 1 to 2 hours or until it doubles in size.",
      "While the dough is rising, prepare the topping by mixing the softened unsalted butter, granulated sugar, all-purpose flour, vanilla extract, and food coloring (if using) in a separate bowl until well combined.",
      "Once the dough has doubled in size, punch it down and divide it into equal portions.",
      "Shape each portion into a ball and place them on a baking sheet lined with parchment paper.",
      "Press each ball down gently to create a flat surface.",
      "Using the topping mixture, divide it into equal portions and shape each portion into a disk.",
      "Place the topping disk on top of each dough ball, gently pressing it down.",
      "Using a knife or a dough cutter, score the topping to create a seashell-like pattern.",
      "Cover the baking sheet with a clean kitchen towel and let the conchas rise for another 30 minutes.",
      "Preheat your oven to 350°F (175°C).",
      "Bake the concha bread in the preheated oven for about 15 to 20 minutes or until they are golden brown.",
      "Let the concha bread cool on a wire rack before serving.",
      "Enjoy the delicious and sweet concha bread as a classic Mexican dessert or breakfast treat!",
    ],
    recipeType: "desserts",
    isFavorite: false,
    isWeekly: false,
    time: "4 hrs",
  },
  {
    id: 12,
    img: Churros,
    title: "Churros",
    description:
      "Crispy and cinnamon-sugar coated fried dough sticks, perfect for dipping.",
    ingredients: [
      "1 cup water",
      "1/2 cup unsalted butter",
      "1/4 teaspoon salt",
      "1 cup all-purpose flour",
      "3 large eggs",
      "1 teaspoon vanilla extract",
      "Vegetable oil, for frying",
      "1/2 cup granulated sugar",
      "1 teaspoon ground cinnamon",
      "Chocolate sauce or dulce de leche for dipping",
    ],
    instructions: [
      "In a saucepan, bring the water, unsalted butter, and salt to a boil.",
      "Reduce the heat to low and add the all-purpose flour. Stir vigorously until the mixture forms a smooth dough.",
      "Remove the saucepan from the heat and let the dough cool for a few minutes.",
      "In a separate small bowl, whisk together the eggs and vanilla extract.",
      "Add the egg mixture to the dough and stir until it is well incorporated and smooth.",
      "Heat vegetable oil in a deep pot or a deep fryer to 375°F (190°C).",
      "Transfer the churro dough to a pastry bag fitted with a large star tip.",
      "Carefully pipe the dough into the hot oil, cutting it with scissors to the desired length.",
      "Fry the churros until they are golden brown and crispy, about 2-3 minutes per side.",
      "Remove the churros from the oil using a slotted spoon and drain them on a paper towel-lined plate.",
      "In a shallow dish, mix the granulated sugar and ground cinnamon for the coating.",
      "While the churros are still warm, roll them in the cinnamon-sugar mixture until they are coated evenly.",
      "Serve the delicious churros with chocolate sauce or dulce de leche for dipping.",
      "Enjoy the crispy and sweet churros as a classic Mexican dessert or snack!",
    ],
    recipeType: "desserts",
    isFavorite: false,
    isWeekly: false,
    time: "45 min",
  },
  {
    id: 13,
    img: MargaritaTart,
    title: "Margarita Tart",
    description:
      "A zesty and refreshing tart inspired by the flavors of a classic margarita cocktail.",
    ingredients: [
      "1 1/2 cups graham cracker crumbs",
      "1/2 cup unsalted butter, melted",
      "1/4 cup granulated sugar",
      "1 can (14 oz) sweetened condensed milk",
      "1/2 cup freshly squeezed lime juice",
      "1/4 cup tequila",
      "1 tablespoon lime zest",
      "1 cup heavy cream",
      "2 tablespoons powdered sugar",
      "Additional lime zest or lime slices for garnish",
    ],
    instructions: [
      "Preheat your oven to 350°F (175°C).",
      "In a bowl, mix the graham cracker crumbs, melted unsalted butter, and granulated sugar until the mixture resembles wet sand.",
      "Press the graham cracker mixture into the bottom and up the sides of a tart pan.",
      "Bake the crust in the preheated oven for about 8-10 minutes or until it is lightly golden and set.",
      "Remove the crust from the oven and let it cool completely.",
      "In a separate bowl, whisk together the sweetened condensed milk, freshly squeezed lime juice, tequila, and lime zest until well combined.",
      "Pour the lime mixture into the cooled tart crust.",
      "Chill the tart in the refrigerator for at least 2 hours to set.",
      "In another bowl, whip the heavy cream and powdered sugar until stiff peaks form.",
      "Spread the whipped cream over the chilled tart.",
      "Garnish the margarita tart with additional lime zest or lime slices for a vibrant touch.",
      "Slice the tart and serve it as a refreshing and zesty dessert.",
      "Enjoy the delightful Margarita Tart with a hint of tequila!",
    ],
    recipeType: "desserts",
    isFavorite: false,
    isWeekly: false,
    time: "90 min",
  },
  {
    id: 14,
    img: Chocoflan,
    imgSmall: ChocoflanSmall,
    title: "Chocoflan",
    description:
      "A luscious and decadent dessert that combines chocolate cake and creamy flan.",
    ingredients: [
      "For the flan layer:",
      "1 can (14 oz) sweetened condensed milk",
      "1 can (12 oz) evaporated milk",
      "4 large eggs",
      "1 teaspoon vanilla extract",
      "For the chocolate cake layer:",
      "1 1/2 cups all-purpose flour",
      "1 cup granulated sugar",
      "1/2 cup unsweetened cocoa powder",
      "1 teaspoon baking powder",
      "1/2 teaspoon baking soda",
      "1/4 teaspoon salt",
      "1 cup buttermilk",
      "1/2 cup vegetable oil",
      "2 large eggs",
      "1 teaspoon vanilla extract",
    ],
    instructions: [
      "Preheat your oven to 350°F (175°C). Grease a Bundt pan with butter or cooking spray.",
      "For the flan layer, blend the sweetened condensed milk, evaporated milk, eggs, and vanilla extract in a blender until smooth. Set aside.",
      "For the chocolate cake layer, in a large mixing bowl, whisk together the all-purpose flour, granulated sugar, cocoa powder, baking powder, baking soda, and salt.",
      "In another bowl, whisk together the buttermilk, vegetable oil, eggs, and vanilla extract.",
      "Pour the wet ingredients into the dry ingredients and mix until just combined.",
      "Pour the flan mixture into the greased Bundt pan.",
      "Carefully pour the chocolate cake batter over the flan mixture, making sure not to mix them together.",
      "Cover the Bundt pan tightly with aluminum foil.",
      "Place the Bundt pan inside a larger roasting pan. Fill the roasting pan with hot water to create a water bath.",
      "Carefully transfer the setup to the preheated oven and bake for about 1 hour and 30 minutes or until a toothpick inserted into the chocolate cake comes out clean.",
      "Remove the Bundt pan from the water bath and let the chocoflan cool to room temperature.",
      "Once cooled, refrigerate the chocoflan for at least 4 hours or overnight.",
      "To serve, carefully invert the chocoflan onto a serving platter, allowing the caramel sauce to drizzle over the dessert.",
      "Slice and enjoy the delightful and indulgent chocoflan!",
    ],
    recipeType: "desserts",
    isFavorite: false,
    isWeekly: true,
    time: "90 min",
  },
  {
    id: 15,
    img: TresLeches,
    title: "Tres Leches Cake",
    description:
      "A moist and milky sponge cake soaked in three kinds of milk and topped with whipped cream.",
    ingredients: [
      "1 cup all-purpose flour",
      "1 1/2 teaspoons baking powder",
      "1/4 teaspoon salt",
      "5 large eggs, separated",
      "1 cup granulated sugar, divided",
      "1 teaspoon vanilla extract",
      "1/3 cup whole milk",
      "For the tres leches mixture:",
      "1 can (14 oz) sweetened condensed milk",
      "1 can (12 oz) evaporated milk",
      "1 cup whole milk",
      "For the whipped cream topping:",
      "1 1/2 cups heavy cream",
      "2 tablespoons powdered sugar",
      "1 teaspoon vanilla extract",
      "Ground cinnamon or cocoa powder for garnish",
    ],
    instructions: [
      "Preheat your oven to 350°F (175°C). Grease and flour a 9x13-inch baking pan.",
      "In a medium bowl, whisk together the all-purpose flour, baking powder, and salt.",
      "In a separate large mixing bowl, beat the egg yolks with 3/4 cup of granulated sugar until the mixture is pale and creamy.",
      "Stir in the vanilla extract and whole milk.",
      "Gradually add the dry flour mixture to the wet ingredients, mixing until just combined.",
      "In another bowl, beat the egg whites until soft peaks form.",
      "Gradually add the remaining 1/4 cup of granulated sugar and continue beating until stiff peaks form.",
      "Gently fold the beaten egg whites into the cake batter, being careful not to deflate the mixture.",
      "Pour the batter into the prepared baking pan.",
      "Bake in the preheated oven for about 25-30 minutes or until a toothpick inserted into the center of the cake comes out clean.",
      "Remove the cake from the oven and let it cool slightly.",
      "In a separate bowl, whisk together the sweetened condensed milk, evaporated milk, and whole milk to create the tres leches mixture.",
      "Using a fork or a skewer, poke several holes all over the surface of the cake.",
      "Slowly pour the tres leches mixture over the cake, allowing it to absorb the liquid.",
      "Cover the cake and refrigerate for at least 2 hours or overnight to allow it to soak up the milky goodness.",
      "In a mixing bowl, whip the heavy cream with powdered sugar and vanilla extract until stiff peaks form.",
      "Spread the whipped cream over the chilled tres leches cake.",
      "Garnish with a sprinkle of ground cinnamon or cocoa powder for added flavor and decoration.",
      "Slice and enjoy the moist and milky Tres Leches Cake as a delightful Mexican dessert!",
    ],
    recipeType: "desserts",
    isFavorite: false,
    isWeekly: false,
    time: "2 hrs",
  },
  {
    id: 16,
    img: Champurrado,
    title: "Champurrado",
    description:
      "A comforting and chocolatey Mexican drink made with masa harina and piloncillo.",
    ingredients: [
      "2 cups water",
      "1 cinnamon stick",
      "1/4 cup masa harina",
      "3 cups milk",
      "1 tablet (about 3 oz) Mexican chocolate (such as Abuelita or Ibarra), chopped",
      "1/4 cup piloncillo or brown sugar",
      "1/2 teaspoon ground cinnamon",
      "Pinch of salt",
    ],
    instructions: [
      "In a saucepan, bring the water and cinnamon stick to a boil.",
      "In a separate small bowl, whisk together the masa harina and 1 cup of milk until it forms a smooth paste.",
      "Pour the masa harina mixture into the boiling water while stirring constantly.",
      "Add the remaining milk, chopped Mexican chocolate, piloncillo or brown sugar, ground cinnamon, and a pinch of salt.",
      "Reduce the heat to low and let the champurrado simmer for about 5-7 minutes, stirring occasionally, until it thickens and the chocolate is fully melted.",
      "Remove the cinnamon stick from the champurrado before serving.",
      "Pour the champurrado into mugs and enjoy the comforting and chocolatey Mexican drink!",
    ],
    recipeType: "drinks",
    isFavorite: false,
    isWeekly: false,
    time: "30 min",
  },
  {
    id: 17,
    img: Margarita,
    title: "Margarita",
    description:
      "A classic and refreshing tequila-based cocktail with lime and orange flavors.",
    ingredients: [
      "2 oz tequila",
      "1 oz triple sec or orange liqueur",
      "3/4 oz freshly squeezed lime juice",
      "1/2 oz simple syrup",
      "Ice",
      "Salt or sugar (for rimming, optional)",
      "Lime slices for garnish",
    ],
    instructions: [
      "If desired, rim a margarita glass with salt or sugar by rubbing a lime slice around the rim and dipping it into a shallow plate of salt or sugar.",
      "Fill a shaker with ice and add the tequila, triple sec or orange liqueur, freshly squeezed lime juice, and simple syrup.",
      "Shake the mixture vigorously for about 10-15 seconds.",
      "Strain the margarita into the prepared glass filled with ice.",
      "Garnish with a lime slice.",
      "Sip and enjoy the classic and refreshing Margarita cocktail!",
    ],
    recipeType: "drinks",
    isFavorite: false,
    isWeekly: false,
    time: "15 min",
  },
  {
    id: 18,
    img: Horchata,
    title: "Horchata",
    description:
      "A creamy and spiced rice milk beverage that's perfect for a hot day.",
    ingredients: [
      "1 cup long-grain white rice",
      "4 cups water",
      "1 cinnamon stick",
      "1/2 cup sweetened condensed milk",
      "1 teaspoon vanilla extract",
      "Ground cinnamon for garnish",
    ],
    instructions: [
      "In a blender, blend the long-grain white rice and water until the rice is broken down into small pieces.",
      "Pour the rice mixture into a pitcher and add the cinnamon stick.",
      "Cover the pitcher and let the rice mixture steep in the refrigerator overnight.",
      "The next day, remove the cinnamon stick from the rice mixture and discard it.",
      "Blend the rice mixture once more until it becomes a smooth liquid.",
      "Stir in the sweetened condensed milk and vanilla extract.",
      "Chill the horchata in the refrigerator for at least 1-2 hours before serving.",
      "Pour the horchata into glasses filled with ice.",
      "Sprinkle ground cinnamon on top for added flavor.",
      "Stir before drinking and enjoy the creamy and spiced Horchata!",
    ],
    recipeType: "drinks",
    isFavorite: false,
    isWeekly: false,
    time: "45 min",
  },
  {
    id: 19,
    img: AquaDeJamaica,
    title: "Agua de Jamaica",
    description: "A refreshing and vibrant hibiscus tea with a hint of citrus.",
    ingredients: [
      "1 cup dried hibiscus flowers (jamaica)",
      "8 cups water, divided",
      "1/2 cup granulated sugar (adjust to taste)",
      "1 cinnamon stick",
      "1 orange, sliced",
      "1 lime, sliced",
      "Ice",
    ],
    instructions: [
      "In a saucepan, bring 4 cups of water to a boil.",
      "Remove the water from the heat and add the dried hibiscus flowers and cinnamon stick.",
      "Let the mixture steep for about 20 minutes.",
      "Strain the hibiscus tea into a pitcher, discarding the flowers and cinnamon stick.",
      "Add the granulated sugar to the pitcher and stir until it dissolves.",
      "Add the remaining 4 cups of water to the pitcher and stir.",
      "Add the sliced orange and lime to the hibiscus tea.",
      "Chill the Agua de Jamaica in the refrigerator for at least 1-2 hours before serving.",
      "Pour the chilled Agua de Jamaica into glasses filled with ice.",
      "Garnish with additional orange and lime slices if desired.",
      "Sip and enjoy the refreshing and vibrant Agua de Jamaica!",
    ],
    recipeType: "drinks",
    isFavorite: false,
    isWeekly: false,
    time: "45 min",
  },
  {
    id: 20,
    img: AquasFrescas,
    imgSmall: AquasFrescasSmall,
    title: "Aguas Frescas",
    description:
      "A variety of fresh fruit-based drinks that are both hydrating and flavorful.",
    ingredients: [
      "Choose one or more of the following fruits:",
      "Watermelon",
      "Cantaloupe",
      "Honeydew melon",
      "Pineapple",
      "Mango",
      "Cucumber",
      "Lime",
      "Oranges",
      "Strawberries",
      "Kiwi",
      "Jicama",
      "Papaya",
      "Guava",
      "Tamarind",
      "1/2 cup granulated sugar (adjust to taste)",
      "4 cups water",
      "Ice",
    ],
    instructions: [
      "Wash and prepare the fruits as needed (remove seeds, peel, etc.).",
      "Cut the fruits into small pieces and place them in a blender.",
      "Add the granulated sugar and water to the blender.",
      "Blend the mixture until it becomes a smooth liquid.",
      "Taste the aguas frescas and adjust the sweetness or add more water if desired.",
      "Chill the aguas frescas in the refrigerator for at least 1-2 hours before serving.",
      "Pour the chilled aguas frescas into glasses filled with ice.",
      "Serve the refreshing and hydrating Aguas Frescas with your favorite fruit flavors!",
    ],
    recipeType: "drinks",
    isFavorite: false,
    isWeekly: true,
    time: "30 min",
  },
  {
    id: 21,
    img: Nachos,
    title: "Nachos",
    description:
      "A Tex-Mex classic, featuring tortilla chips topped with melted cheese and various toppings.",
    ingredients: [
      "Tortilla chips",
      "2 cups shredded cheddar or Monterey Jack cheese",
      "1 cup cooked and seasoned ground beef or shredded chicken",
      "1/2 cup black beans, drained and rinsed",
      "1/4 cup sliced jalapeños (optional)",
      "1/4 cup diced tomatoes",
      "1/4 cup chopped green onions",
      "Sour cream and guacamole for serving",
    ],
    instructions: [
      "Preheat your oven to 375°F (190°C).",
      "Spread a layer of tortilla chips on a large baking sheet.",
      "Evenly distribute the shredded cheese over the tortilla chips.",
      "Add the cooked and seasoned ground beef or shredded chicken on top of the cheese.",
      "Sprinkle the black beans and sliced jalapeños (if using) over the nachos.",
      "Bake in the preheated oven for about 10-15 minutes or until the cheese is fully melted and bubbly.",
      "Remove the nachos from the oven and top them with diced tomatoes and chopped green onions.",
      "Serve the nachos hot with sour cream and guacamole for dipping.",
      "Enjoy the delicious and indulgent Nachos as a popular Tex-Mex appetizer or snack!",
    ],
    recipeType: "texmex",
    isFavorite: false,
    isWeekly: false,
    time: "30 min",
  },
  {
    id: 22,
    img: Taquitos,
    title: "Taquitos",
    description:
      "Crispy rolled tortillas that are filled with seasoned meat and cheese, perfect for dipping.",
    ingredients: [
      "Corn tortillas",
      "2 cups cooked and seasoned shredded chicken or beef",
      "1 cup shredded cheddar or Monterey Jack cheese",
      "1 teaspoon chili powder",
      "1/2 teaspoon ground cumin",
      "1/2 teaspoon garlic powder",
      "1/4 teaspoon salt",
      "Vegetable oil for frying",
      "Sour cream and salsa for serving",
    ],
    instructions: [
      "In a mixing bowl, combine the cooked and seasoned shredded chicken or beef, shredded cheese, chili powder, ground cumin, garlic powder, and salt.",
      "Place a small amount of the filling mixture on one end of a corn tortilla.",
      "Roll up the tortilla tightly, securing the taquito with a toothpick if needed.",
      "Repeat the process with the remaining tortillas and filling.",
      "In a skillet, heat vegetable oil over medium-high heat.",
      "Carefully fry the taquitos in the hot oil until they are golden brown and crispy on all sides.",
      "Remove the taquitos from the oil and let them drain on a paper towel-lined plate.",
      "Serve the taquitos hot with sour cream and salsa for dipping.",
      "Enjoy the crispy and flavorful Taquitos as a Tex-Mex appetizer or snack!",
    ],
    recipeType: "texmex",
    isFavorite: false,
    isWeekly: false,
    time: "45 min",
  },
  {
    id: 23,
    img: FritoPie,
    imgSmall: FritoPieSmall,
    title: "Frito Pie",
    description:
      "A hearty and flavorful Tex-Mex dish, featuring Fritos topped with chili and cheese.",
    ingredients: [
      "1 bag (9.25 oz) Fritos corn chips",
      "2 cups homemade or canned chili",
      "1 cup shredded cheddar or Monterey Jack cheese",
      "1/4 cup diced onions",
      "1/4 cup pickled jalapeños (optional)",
      "Sour cream and chopped cilantro for garnish",
    ],
    instructions: [
      "Preheat your oven to 375°F (190°C).",
      "Spread a layer of Fritos corn chips on the bottom of a baking dish.",
      "Pour the homemade or canned chili over the Fritos, covering them evenly.",
      "Sprinkle the shredded cheese on top of the chili.",
      "Add the diced onions and pickled jalapeños (if using) as an extra layer of flavor.",
      "Bake the Frito Pie in the preheated oven for about 10-15 minutes or until the cheese is melted and bubbly.",
      "Remove the baking dish from the oven and let the Frito Pie cool slightly.",
      "Garnish the Frito Pie with sour cream and chopped cilantro.",
      "Serve the delicious and hearty Frito Pie as a Tex-Mex comfort food!",
    ],
    recipeType: "texmex",
    isFavorite: false,
    isWeekly: true,
    time: "30 min",
  },
  {
    id: 24,
    img: Enchiladas,
    title: "Enchiladas",
    description:
      "Tortillas filled with meat, beans, or cheese, smothered in sauce and baked to perfection.",
    ingredients: [
      "8 corn tortillas",
      "2 cups cooked and seasoned shredded chicken, beef, or beans",
      "1 cup shredded cheddar or Monterey Jack cheese",
      "1 can (14 oz) enchilada sauce",
      "1/4 cup chopped black olives (optional)",
      "1/4 cup chopped fresh cilantro",
      "Sour cream and sliced avocado for serving",
    ],
    instructions: [
      "Preheat your oven to 375°F (190°C).",
      "In a microwave-safe plate, stack the corn tortillas and cover them with a damp paper towel.",
      "Microwave the tortillas for about 1 minute to soften them.",
      "In a bowl, combine the cooked and seasoned shredded chicken, beef, or beans with half of the shredded cheese.",
      "Place a portion of the filling mixture on one end of a softened corn tortilla.",
      "Roll up the tortilla tightly and place it seam-side down in a baking dish.",
      "Repeat the process with the remaining tortillas and filling.",
      "Pour the enchilada sauce over the rolled tortillas, making sure they are fully covered.",
      "Sprinkle the remaining shredded cheese and chopped black olives (if using) over the enchiladas.",
      "Bake the enchiladas in the preheated oven for about 20 minutes or until the cheese is melted and bubbly.",
      "Remove the baking dish from the oven and let the enchiladas cool slightly.",
      "Garnish the enchiladas with chopped cilantro.",
      "Serve the delicious and saucy Enchiladas with sour cream and sliced avocado on the side.",
      "Enjoy the flavorful and comforting Tex-Mex Enchiladas!",
    ],
    recipeType: "texmex",
    isFavorite: false,
    isWeekly: false,
    time: "45 min",
  },
  {
    id: 25,
    img: Tacos,
    title: "Tacos",
    description:
      "A Tex-Mex version of tacos, featuring seasoned ground beef and classic toppings.",
    ingredients: [
      "1 lb ground beef",
      "1 packet taco seasoning mix",
      "1/2 cup water",
      "Hard taco shells or soft tortillas",
      "Shredded lettuce",
      "Diced tomatoes",
      "Shredded cheddar cheese",
      "Sour cream",
      "Salsa",
    ],
    instructions: [
      "In a skillet, brown the ground beef over medium heat until fully cooked.",
      "Drain any excess grease from the cooked ground beef.",
      "Add the taco seasoning mix and water to the skillet with the ground beef.",
      "Stir everything together and let it simmer for a few minutes until the mixture thickens.",
      "Preheat your oven to 350°F (175°C) if using hard taco shells.",
      "If using hard taco shells, place them on a baking sheet and warm them in the preheated oven for a few minutes.",
      "If using soft tortillas, warm them in a separate skillet or the microwave.",
      "Fill the taco shells or tortillas with the seasoned ground beef.",
      "Top the tacos with shredded lettuce, diced tomatoes, shredded cheddar cheese, sour cream, and salsa.",
      "Serve the American Tacos as a Tex-Mex twist on the classic favorite!",
    ],
    recipeType: "texmex",
    isFavorite: false,
    isWeekly: false,
    time: "30 min",
  },
];
